export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const UPDATE_BALANCE = 'UPDATE_BALANCE';
export const SWITCH_NETWORK = 'SWITCH_NETWORK';
export const SHOW_POPUP = 'SHOW_POPUP';
export const HIDE_POPUP = 'HIDE_POPUP';
export const SWITCH_LOGGED_IN = 'SWITCH_LOGGED_IN';
export const UPDATE_LATEST_TRANSACTIONS = 'UPDATE_LATEST_TRANSACTIONS';
export const SET_SUBACCOUNTS = 'SET_SUBACCOUNTS';

