import {onBeforeLoad} from '../support/mock_chrome.js';
import {login,loginAndLogout} from '../login';

const openTokensPage = () => {
    login()
    cy
    .visit('popup/popup.html',{onBeforeLoad})
    .get('#settings')
    .click()
    .get('.toTokens')
    .click()
}

describe("Test cases for adding fungible tokens functionality", () => {

    it("open add tokens page", () => {
        openTokensPage()
        cy
        .get('.token-add-form')
        .should('be.visible')
        .get('.toAccount')
        .should('be.visible')
        .get('.to-confirm-add')
        .should('be.visible')
    })

    it("open add tokens page and click back button", () => {
        openTokensPage()
        cy
        .get('.backbutton')
        .should('be.visible')
        .click()
        .get('.ae-card.primary')
        .should('be.visible')
    })

    it("validate form inputs", () => {
        openTokensPage()
        cy
        .get('.to-confirm-add')
        .click()
        .get('.ae-modal-light')
        .should('be.visible')
        .get('.ae-modal-light .buttons button')
        .click()
        .get('.ae-modal-light')
        .should('not.be.visible')
        .get('.token-contract')
        .type('000')
        .get('.token-symbol')
        .type('TST')
        .get('.token-precision')
        .type(30)
        .get('.to-confirm-add')
        .click()
        .get('.ae-modal-light')
        .should('be.visible')
    })

    it("validate correct entered contract address", () => {
        openTokensPage()
        cy
        .get('.token-symbol')
        .type('TST')
        .get('.token-precision')
        .clear()
        .type(5)
        .get('.token-contract')
        .type('1234')
        .get('.to-confirm-add')
        .click()
        .get('.ae-modal-light')
        .should('be.visible')
        .get('.ae-modal-light .buttons button')
        .click()
        .get('.token-contract')
        .type('ct_2CC7FPsumg5azo7xNH6XS9wCnzFqVCdE4WrKzrUk6Z4jNeazF')
        // .get('.to-confirm-add')
        // .click()
        // .get('.ae-modal-light')
        // .should('be.visible')
        // .get('.ae-modal-light .buttons button')
        // .click()
        // .get('.token-contract')
        // .type('ct_2CC7FPsumg5azo7xNH6XS9wCnzFqVCdE4WrKzrUk6Z4jNeazF88')
        // .get('.to-confirm-add')
        // .click()
        // .get('.ae-modal-light')
        // .should('be.visible')
        // .get('.ae-modal-light .buttons button')
        // .click()
        // .get('.ae-modal-light')
        // .should('not.be.visible')
    })

    it("validate correct entered token symbol", () => {
        openTokensPage()
        cy
        .get('.token-contract')
        .type('ct_2CC7FPsumg5azo7xNH6XS9wCnzFqVCdE4WrKzrUk6Z4jNeazF9')
        .get('.ae-loader')
        .should('not.be.visible')
        .get('.ae-modal-light')
        .should('be.visible')
        .get('.ae-modal-light .buttons button')
        .click()
        .get('.ae-modal-light')
        .should('not.be.visible')
        .get('.token-precision')
        .clear()
        .type(5)
        .get('.to-confirm-add')
        .click()
        .get('.ae-modal-light')
        .should('be.visible')
        .get('.ae-modal-light .buttons button')
        .click()
        .get('.token-symbol')
        .type('AEEEEEEEEEEEEEEEEE')
        .get('.to-confirm-add')
        .click()
        .get('.ae-modal-light')
        .should('be.visible')
        .get('.ae-modal-light .buttons button')
        .click()
        .get('.ae-modal-light')
        .should('not.be.visible')
    })

    it("validate correct entered token precision", () => {
        openTokensPage()
        cy
        .get('.token-contract')
        .type('ct_2CC7FPsumg5azo7xNH6XS9wCnzFqVCdE4WrKzrUk6Z4jNeazF9')
        .get('.ae-loader')
        .should('not.be.visible')
        .get('.ae-modal-light')
        .should('be.visible')
        .get('.ae-modal-light .buttons button')
        .click()
        .get('.ae-modal-light')
        .should('not.be.visible')
        .get('.token-symbol')
        .type('TST')
        .get('.token-precision')
        .clear()
        .type('a')
        .get('.to-confirm-add')
        .click()
        .get('.ae-modal-light')
        .should('be.visible')
        .get('.ae-modal-light .buttons button')
        .click()
        .get('.token-precision')
        .clear()
        .type('-5')
        .get('.to-confirm-add')
        .click()
        .get('.ae-modal-light')
        .should('be.visible')
        .get('.ae-modal-light .buttons button')
        .click()
        .get('.token-precision')
        .clear()
        .type('38')
        .get('.to-confirm-add')
        .click()
        .get('.ae-modal-light')
        .should('be.visible')
        .get('.ae-modal-light .buttons button')
        .click()
        .get('.token-precision')
        .clear()
        .type(2)
        .get('.to-confirm-add')
        .click()
        .get('.ae-loader')
    })

    it("open login", () => {
        cy.visit('popup/popup.html',{onBeforeLoad})
    })
})